title: Spain in the Spring
author: PJ Mason
email: pjmason1220@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Trip to Barcelona

# social links
twitter_username: @pjmason1220
github_username:  @pjmason1220

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
